# Generated by Django 3.1 on 2021-03-01 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_auto_20210301_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='updated_by',
        ),
    ]
